### ISSUE TITLE
[RFC] Support selector 

### ISSUE THREAD

**Issue by jessy1092** [jessy1092/react-redux-hooks#3]
`useRedux` could pass selector to return specific state.
```javascript
const [toggle, dispatch] = useRedux((state) => state.toggle);
```

Pors.
- Can reuse selector
- Improve performance. It could combine with #2

**Comment by jimmed** [comment]
**N.B.** I would have raised a new issue for this, but I think the feature I'm proposing here is quite similar to the selector support you have proposed.

### Motivation

Since building some simple toy apps using react-redux-hooks, I've been thinking about the best way to offer a feature similar to `connect` from react-redux.

Essentially, reusable memoized selectors are deeply desirable for use with Redux for reasons that are [well-documented elsewhere](https://github.com/reduxjs/reselect#motivation-for-memoized-selectors), mostly around performance, but also (relevant to this case), around developer experience.

However, selecting data is only one half of the story; we also need to dispatch actions back. One of the things I love about react-redux is that I have a choice of:

 - Calling dispatch directly within my component, passing it an action somehow
 - Calling a method defined within mapDispatchToProps, which can use dispatch:
   - Manually; by defining `mapDispatchToProps` as a function
   - Automatically; by defining `mapDispatchToProps` as an object

Either way, this flexibility is something that I've been missing in react-redux-hooks.

### _My_ Motivations

It's common in applications based on react-redux to define "containers", namely higher-order components that wrap (typically stateless) components with the ability to read from the redux store by using a predefined selector (`mapStatetoProps`), and an optional set of methods to dispatch actions back to the store (`mapDispatchToProps`). Aside from writing `mapXToProps` over and over, this pattern has a lovely developer experience, especially as you can re-use (and compose together) these containers with different components.

A very common example of this in classic react-redux is something like:

```js
const withCurrentUser = connect(
  (state) => ({ username: state.currentUser.name }), // selector
  { login, logout } // action creators
)
```

In order to achieve something similar with hooks, I am proposing a `createReduxHook` function which might behave something like:

```js
const useCurrentUser = createReduxHook(
  (state) => ({ username: state.currentUser.name }), // selector
  { login, logout } // action creators
)
```

Note that the signature is _identical_ to that of `connect`; the difference is the return value. A basic implementation might look something like:

```js
const createReduxHook = (selector, actions) => () => {
  const [state, dispatch] = useRedux()
  return [selector(state), bindActionCreators(actions, dispatch)]
}
```

Naturally, this implementation only supports the object signature for `mapDispatchToProps`; in order to support the functional version we would need to extend it a little to something like:

```js
const createReduxHook = (selector, actions) => () => {
  const [state, dispatch] = useRedux()
  const selectedState = selector(state)
  const boundActions = typeof actions === 'function'
    ? actions(dispatch)
    : bindActionCreators(action, dispatch)

  return [selectedState, boundActions]
}
```

Does this fit with your ideas for the library? Please let me know!

**Comment by jessy1092** [comment]
@jimmed  Awesome. I like your idea. And could combine Reselect and redux method is the best thing.

I have no reason to reject this.  💯 

For some detail. I think we should just implement in `useRedux`. For user, just use HOF to create `useRedux`

For implementation,
```javascript
// New useRedux
const useRedux = (selector, actions) => {
  const [state, dispatch] = useReduxCore() // useReduxCore is the old useRedux 
  const selectedState = typeof selector !== 'function' ? state : selector(state);
  
  if (typeof actions === 'undefined') {
     return [selectedState, dispatch];
  }

  const boundActions = typeof actions === 'function'
    ? actions(dispatch)
    : bindActionCreators(actions, dispatch)

  return [selectedState, boundActions]
}
```

And we could use as usual. But also extendable.
```javascript
const [{username}, dispatchers] = useRedux(
  (state) => ({ username: state.currentUser.name }), // selector
  { login, logout } // action creators
)
```

User can also create its own hooks by HOF
```javascript
const createReduxHook = (selector, actions) => () => useRedux(selector, actions);

const useCurrentUser = createReduxHook(
  (state) => ({ username: state.currentUser.name }), // selector
  { login, logout } // action creators
)
```
Or just import as alias
```javascript
import {useRedux as useCurrentUser} from 'react-redux-hooks';

const [{username}, actions] = useCurrentUser(
  (state) => ({ username: state.currentUser.name }), // selector
  { login, logout } // action creators
)
```

How do you think? 😄 

Anyway, thanks for your propose. It is a greate idea!! I can wait to see it.

**Comment by jimmed** [comment]
That looks like an excellent API! I have some downtime over the coming winter holidays, so I should be able to spend an hour or two knocking this together and testing it out.

 - [ ] <-- watch this space

**Comment by jessy1092** [comment]
@jimmed I just publish 0.2.0 to contain this feature. You could try it now. :)
